name: grahame
favicon: null
layout_spectrum: 0.90886
typography_spectrum: 0.57514
title: Grahame Murray
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-8100748-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313234'
    - '#030303'
    - '#b88884'
    - '#977067'
    - '#684c4a'
  brandStrength: 0.40788751537911594
  lightness: 0.2337712193839252
  saturation: 0.625
  rhythmicContrast: 0.678342709550634
purpose: []
