name: grahame
favicon: null
layout_spectrum: 0.5485882142093033
typography_spectrum: 0.7861483215820044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.40788751537911594
  lightness: 0.2337712193839252
  saturation: 0.6495533578563482
  rhythmicContrast: 0.678342709550634
purpose: []
